##################################################
#                                                #
#                  Codis-Proxy                   #
#                                                #
##################################################
[proxy]
# Set Codis Product Name/Auth.
product_name = "codis-demo"
product_auth = ""

# Set auth for client session
#   1. product_auth is used for auth validation among codis-dashboard,
#      codis-proxy and codis-server.
#   2. session_auth is different from product_auth, it requires clients
#      to issue AUTH <PASSWORD> before processing any other commands.
session_auth = ""

# Set bind address for admin(rpc), tcp only.
admin_addr = "0.0.0.0:11080"

# Set bind address for proxy, proto_type can be "tcp", "tcp4", "tcp6", "unix" or "unixpacket".
proto_type = "tcp4"
addr = "127.0.0.1:19000"

protocol_type = "tcp4"
# Set datacenter of proxy.
datacenter = ""

# Set max number of alive sessions.
max_clients = 1000

# Set max offheap memory size. (0 to disable)
max_offheap_size = "1024mb"

# Set heap placeholder to reduce GC frequency.
heap_placeholder = "256mb"

[backend]
# Proxy will ping backend redis (and clear 'MASTERDOWN' state) in a predefined interval. (0 to disable)
ping_period = "5s"

# Set backend recv buffer size & timeout.
recv_bufsize = "128kb"
recv_timeout = "30s"

# Set backend send buffer & timeout.
send_bufsize = "128kb"
send_timeout = "30s"

# Set backend pipeline buffer size.
max_pipeline = 20480

# Set backend never read replica groups, default is false
primary_only = false

# Set backend parallel connections per server
primary_parallel = 1
replica_parallel = 1

# Set backend tcp keepalive period. (0 to disable)
keepalive_period = "75s"

# Set number of databases of backend.
number_databases = 16

[session]
# If there is no request from client for a long time, the connection will be closed. (0 to disable)
# Set session recv buffer size & timeout.
recv_bufsize = "128kb"
recv_timeout = "30m"

# Set session send buffer size & timeout.
send_bufsize = "64kb"
send_timeout = "30s"

# Make sure this is higher than the max number of requests for each pipeline request, or your client may be blocked.
# Set session pipeline buffer size.
max_pipeline = 10000

# Set session tcp keepalive period. (0 to disable)
keepalive_period = "75s"

# Set session to be sensitive to failures. Default is false, instead of closing socket, proxy will send an error response to client.
break_on_failure = false

[metrics]
# Set metrics server (such as http://localhost:28000), proxy will report json formatted metrics to specified server in a predefined period.
report_server = ""
report_period = "1s"

# Set influxdb server (such as http://localhost:8086), proxy will report metrics to influxdb.
report_influxdb_server = ""
report_influxdb_period = "1s"
report_influxdb_username = ""
report_influxdb_password = ""
report_influxdb_database = ""

# Set statsd server (such as localhost:8125), proxy will report metrics to statsd.
report_statsd_server = ""
report_statsd_period = "1s"
report_statsd_prefix = ""
