name: UT

on:
  pull_request:
  push:
    branches:
      - "main"
      - "releases/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-cargo-dependencies
        with:
          path: |
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/registry/
            ~/.cargo/git/
            ~/.cargo/bin/
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Test pika-proxy
        run: cargo llvm-cov -p pika-proxy --lcov --output-path pika-proxy.info
      - name: Collection Coverage
        run: cargo llvm-cov --no-run --lcov --output-path lcov.info

      - name: Save coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./*.info
          if-no-files-found: error

  upload_codecov:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    strategy:
      matrix:
        crate: [pika-proxy]

    steps:
      - uses: actions/checkout@v3

      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.crate }}.info
          flags: ${{ matrix.crate }}
          fail_ci_if_error: true

      - name: Upload sum to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          fail_ci_if_error: true